import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/src/components/query-provider/query-provider";

import { Roboto } from "next/font/google";

import ClientOnly from "./clientOnly";
import Providers from "@/src/components/ui/bProgress";
import { SyncCartOnLogin } from "@/src/components/cart/syncCartOnLoogin";
import { CheckoutProvider } from "@/src/components/hooks/useCheckoutHooks";
import ProductDetailsProvider from "@/src/components/productDetails/components/context";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}  antialiased`}>
        <Providers>
          <QueryProvider>
            <CheckoutProvider>
              <ProductDetailsProvider>
                <ClientOnly>
                  <SyncCartOnLogin />

                  {children}
                </ClientOnly>
              </ProductDetailsProvider>
            </CheckoutProvider>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
